FROM node:24-alpine

RUN apk add --no-cache ca-certificates libc6-compat

RUN mkdir -p \
        /usr/local/awsmock/bin \
        /usr/local/awsmock/etc \
        /usr/local/awsmock/log

COPY cmake-build-release/awsmock-lrt /usr/local/awsmock/bin/awsmock-lrt
RUN chmod +x /usr/local/awsmock/bin/awsmock-lrt

COPY docker/awsmock.json /usr/local/awsmock/etc/awsmock.json

ENV PATH="/usr/local/awsmock/bin:${PATH}"

EXPOSE 8080

ENTRYPOINT ["/usr/local/awsmock/bin/awsmock-lrt"]
