FROM amazonlinux:2023

RUN dnf install -y ca-certificates java-21-amazon-corretto-headless && dnf clean all

RUN mkdir -p \
        /usr/local/awsmock/bin \
        /usr/local/awsmock/etc \
        /usr/local/awsmock/log

COPY cmake-build-release/awsmocklrt /usr/local/awsmock/bin/awsmocklrt
RUN chmod +x /usr/local/awsmock/bin/awsmocklrt

COPY docker/awsmock.json /usr/local/awsmock/etc/awsmock.json

ENV PATH="/usr/local/awsmock/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/lib/jvm/java-21-amazon-corretto/lib/server"

EXPOSE 8080

ENTRYPOINT ["/usr/local/awsmock/bin/awsmocklrt"]
