FROM python:3.14

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates openjdk-21-jre-headless && rm -rf /var/lib/apt/lists/*

RUN mkdir -p \
        /usr/local/awsmock/bin \
        /usr/local/awsmock/etc \
        /usr/local/awsmock/log

COPY cmake-build-release/awsmocklrt /usr/local/awsmock/bin/awsmocklrt
RUN chmod +x /usr/local/awsmock/bin/awsmocklrt

COPY docker/awsmock.json /usr/local/awsmock/etc/awsmock.json

ENV PATH="/usr/local/awsmock/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/lib/jvm/java-21-openjdk-amd64/lib/server"

EXPOSE 8080

ENTRYPOINT ["/usr/local/awsmock/bin/awsmocklrt"]
