FROM alpine:3.20

RUN apk add --no-cache ca-certificates

RUN mkdir -p \
        /usr/local/awsmock/bin \
        /usr/local/awsmock/etc \
        /usr/local/awsmock/log

COPY cmake-build-release/awsmocklrt /usr/local/awsmock/bin/awsmocklrt
RUN chmod +x /usr/local/awsmock/bin/awsmocklrt

COPY docker/awsmock.json /usr/local/awsmock/etc/awsmock.json

ENV PATH="/usr/local/awsmock/bin:${PATH}"

EXPOSE 8080

ENTRYPOINT ["/usr/local/awsmock/bin/awsmocklrt"]
